[[redirects]]
from = "/reveal-test/*"
to = "https://timebertt-talk-reveal-test.netlify.app/:splat"
status = 200

[[redirects]]
from = "/credentials-rotation/*"
to = "https://talk-credentials-rotation.netlify.app/:splat"
status = 200

[[redirects]]
from = "/controller-sharding-lightning/*"
to = "https://talk-controller-sharding-lightning.netlify.app/:splat"
status = 200

[[redirects]]
from = "/platform-engineering/*"
to = "https://talk-platform-engineering.netlify.app/:splat"
status = 200

# === talk-controller-sharding ===
# version for ContainerDays 2025 (branch deploy)
[[redirects]]
from = "/controller-sharding/containerdays-2025/*"
to = "https://containerdays-2025--talk-controller-sharding.netlify.app/:splat"
status = 200

# main version, not tied to any event
[[redirects]]
from = "/controller-sharding/*"
to = "https://talk-controller-sharding.netlify.app/:splat"
status = 200
